openapi: 3.1.0
info:
  version: 1.0.0
  title: Products app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Products store
tags:
  - name: products
    description: Operations with products
servers:
  - url: http://localhost:3000
paths:
  /products:
    get:
      $ref: '../swagger/paths/get.yaml'
    post:
      $ref: '../swagger/paths/post.yaml'
  /products/{id}:
    get:
      $ref: ../swagger/paths/{id}/get.yaml
    patch:
      $ref: '../swagger/paths/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
